// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERrd2CCQfJ_sUFJTULupVjdizOREzBiY',
    appId: '1:189832307724:web:3bb532373f48b8e5ebfa29',
    messagingSenderId: '189832307724',
    projectId: 'septismart-aecb1',
    authDomain: 'septismart-aecb1.firebaseapp.com',
    databaseURL: 'https://septismart-aecb1-default-rtdb.firebaseio.com',
    storageBucket: 'septismart-aecb1.firebasestorage.app',
    measurementId: 'G-Z962FM6ZM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tE6104q3LYt77YCqSNrUCP2rz7winjk',
    appId: '1:189832307724:android:1febebd8932c9166ebfa29',
    messagingSenderId: '189832307724',
    projectId: 'septismart-aecb1',
    databaseURL: 'https://septismart-aecb1-default-rtdb.firebaseio.com',
    storageBucket: 'septismart-aecb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8hT_X45F4NxV7oLMeGjVGj5et5gbwaMU',
    appId: '1:189832307724:ios:9bdca778936b50d1ebfa29',
    messagingSenderId: '189832307724',
    projectId: 'septismart-aecb1',
    databaseURL: 'https://septismart-aecb1-default-rtdb.firebaseio.com',
    storageBucket: 'septismart-aecb1.firebasestorage.app',
    iosBundleId: 'com.example.septismart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8hT_X45F4NxV7oLMeGjVGj5et5gbwaMU',
    appId: '1:189832307724:ios:9bdca778936b50d1ebfa29',
    messagingSenderId: '189832307724',
    projectId: 'septismart-aecb1',
    databaseURL: 'https://septismart-aecb1-default-rtdb.firebaseio.com',
    storageBucket: 'septismart-aecb1.firebasestorage.app',
    iosBundleId: 'com.example.septismart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERrd2CCQfJ_sUFJTULupVjdizOREzBiY',
    appId: '1:189832307724:web:0996cf5db875fa8aebfa29',
    messagingSenderId: '189832307724',
    projectId: 'septismart-aecb1',
    authDomain: 'septismart-aecb1.firebaseapp.com',
    databaseURL: 'https://septismart-aecb1-default-rtdb.firebaseio.com',
    storageBucket: 'septismart-aecb1.firebasestorage.app',
    measurementId: 'G-SD915PQQ6G',
  );
}
