name: septismart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  provider: ^6.1.2

  firebase_database: ^12.0.0
  percent_indicator: ^4.2.3
  http: ^1.2.2
  fl_chart: ^0.69.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/septic_system.png
    - assets/emergency_services.json
    
